### ISSUE TITLE
Fatal error in examples?

### ISSUE THREAD

**Issue by mburdett555** [arronwoods/php-cif-parser#1]

**Comment by arronwoods** [comment]
Hi @mburdett555, hope you managed to figure out what was wrong?

**Comment by mburdett555** [comment]
Hi @rb-cohen thank you for your reply, 
I am displaying the cif data ok now
Wasnt sure why it was writing out "aaaaaaaaaaaa" however upon closer inspection it is the $record->identity;
I can change what is echoed, and echo everything by just echo $record;
However I will need to read up on php arrays as I am quite new to php
In the end I am quite simply looking to get a list of services which go through a train station which is searched using html form then use php GET to search for those with that tiploc code
I am getting all of the below output with just echo $record in schedules.php but is this all that is in the CIF file?
What exactly does the schedule.php file get from the cif file? Thank you in advance
I have also sent you a contact enquiry through your blog site.

{"identity":"AA","transaction":"N","train_uid":"P40094","associated_train_uid":"P40368","association_start_date":"121209","association_end_date":"130512","association_days":"0000001","association_category":"JJ","association_date_ind":"S","association_location":"MCHYNLT","base_location_suffix":" ","association_location_suffix":" ","diagram_type":"T","association_type":"P","space":" ","stp_indicator":"P"}

**Comment by arronwoods** [comment]
@mburdett555 Sorry, the contact form was set to go to an old email address. :( Could you re-send the email if possible please?

The schedule file only provides that information, it is then supplemented by other CIF files for stations and trains. 

You have probably already come across this, but http://data.atoc.org/how-to provides some good information on the format of the file and what each field represents. The php-cif-parser library is generic, but those example files should get you the raw info out of the files based on the CIF definition used by ATOC. 

Once you have the raw info you would probably need to store it (or a sub-section of it) in a database to allow you to quickly query for the info you need.

**Comment by mburdett555** [comment]
Thankyou
I have downloaded the data in the rail delivery group but it wasnt in CIF format, but rather numerous other formats. 
I shall come back to this on Monday with a fresh head :-) Thank you for your replies
Best Regards
Matt B
